# Generated by Django 2.2.5 on 2020-02-17 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarFooFooModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barfoo4', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar1', models.IntegerField(blank=True, choices=[(1, 'Number_1'), (2, 'Number_2')], null=True)),
                ('bar2', models.CharField(blank=True, max_length=255)),
                ('bar3', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bar4', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo1', models.IntegerField(blank=True, null=True)),
                ('foo2', models.CharField(choices=[('val1', 'Value1'), ('val2', 'Value2')], max_length=5)),
                ('foo3', models.DecimalField(decimal_places=4, max_digits=10)),
                ('foo4', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MixedFooBarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbar', models.ManyToManyField(to='convertable_model.BarModel')),
                ('barfoo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='convertable_model.BarFooFooModel')),
                ('foofoo', models.ManyToManyField(to='convertable_model.FooModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooBarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foobar2', models.CharField(blank=True, max_length=25)),
                ('foobar3', models.DecimalField(decimal_places=4, max_digits=10)),
                ('foobar4', models.DateTimeField(auto_now=True)),
                ('foobar1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='convertable_model.FooModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='barfoofoomodel',
            name='barfoo1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='convertable_model.BarModel'),
        ),
    ]
